### ISSUE TITLE
Remove usage of CallableHandler?

### ISSUE THREAD

**Issue by shadowhand** [middlewares/request-handler#3]
Given that HTTP factories exist, why do we need to use `CallableHandler` to execute the handler Why not simplify the execution path and force the handler to return a `ResponseInterface`?

**Comment by shadowhand** [comment]
On a similar subject, why not drop the resolver and simply say the following?

> The handler must be callable **or** an implementation of `ContainerInterface` must be provided to the middleware to resolve the handler.

**Comment by oscarotero** [comment]
`CallableHandler` is used by many middlewares: errorHandler, routes, shutdown, etc, so it's better to have this helper shared by all these libraries than duplicate code. It's also easier for the end user (at least in my experience) to return or echo a string than having to create a response.

I'm more open about the resolver. It's shared by other middlewares, and includes some aditional features, [like reflectionResolver](https://github.com/middlewares/utils/blob/master/src/CallableResolver/ReflectionResolver.php). But we can have the same functionality providing a Container to instantiate the classes and return the ready to use callables.

**Comment by shadowhand** [comment]
> It's also easier for the end user (at least in my experience) to return or echo a string than having to create a response.

IMO, this should really be up to the user, rather than a side effect of using the middleware. PSR-17 factories make it really easy to create responses. Besides, the response body is not the only concern. What about the `Content-Type` header? There's no way to infer that from a string.

**Comment by oscarotero** [comment]
`CallableHandler` can do all these things. The following examples are valid:

```php
//echo and/or return strings
function handler () {
    echo 'Hello ';
    return 'world';
}

//return a response
function handler () {
    $response = new Response();
    $response->getBody()->write('Hello world');
    return $response->withHeader('Content-Type', 'text/html');
}

//echo content and return a response
function handler () {
    $response = new Response();
    echo 'Hello world'
    return $response->withHeader('Content-Type', 'text/html');
}

//or even mix echo and response content.
function handler () {
    $response = new Response();
    $response->getBody()->write('Hello ');
    echo 'world'
    return $response->withHeader('Content-Type', 'text/html');
}
```

You're asking not to add new abilities, but remove some features for none. For the previous examples, your suggestion would throw an exception in the first case, works fine in the second one, return an empty response in the third case (because the output is not captured) and return a response with just partial content in the fourth case.

I think it's fine to keep this functionality and let the user to choose what to use. If you want to be strict about what the callable must return, just use return typing:

```php
function handler (): ResponseInterface
{
    return 'string'; //throws an exception.
}
```

PSR-17 will ease the creation of responses, but it's not released yet (as stable). I've planned to add a new option to all middlewares that need to create responses to set a `ResponseFactoryInterface`, but I'm waiting until the final interface is approved. Meanwhile, I prefer to rely in a centralized solution (`Middlewares\Utils\Factory`) because it's easier to update to possible new versions.

**Comment by shadowhand** [comment]
> PSR-17 will ease the creation of responses, but it's not released yet (as stable).

Neither is PSR-15. :)

**Comment by oscarotero** [comment]
Ok, finally released a new version with some changes:
- I've removed the `CallableResolverInterface` and now this relies only in a psr-11 `ContainerInterface`.
- Only `MiddlewareInterface` and `RequestHandlerInterface` are allowed as request handler. The first one will continue with the delegate request handler, the second don't. So the user can decide what to use in each case.
- If no `ContainerInterface` is provided, [this one will be used](https://github.com/middlewares/utils/blob/master/src/RequestHandlerContainer.php) that works similar as how it did until now.

**Comment by shadowhand** [comment]
I really like these changes @oscarotero, feels much more reliable and usable for integration with framework code. 🎉
